name: 'flood_forecasting'
version: '1.0.0'

profile: 'flood_forecasting'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  flood_forecasting:
    +schema: seeds

models:
  flood_forecasting:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

flags:
  send_anonymous_usage_stats: false
