flood_forecasting:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      threads: 4
      settings:
        memory_limit: "30GB"
        preserve_insertion_order: false
