-- GAGES-II soil attributes
select
    STAID as SITE_ID,
    AWCAVE as SOIL_WATER_CAPACITY_AVG,
    PERMAVE as SOIL_PERMEABILITY_AVG,
    BDAVE as BULK_DENSITY_AVG,
    OMAVE as ORGANIC_MATTER_AVG,
    WTDEPAVE as WATER_TABLE_DEPTH_AVG,
    ROCKDEPAVE as ROCK_DEPTH_AVG,
    CLAYAVE as CLAY_PCT_AVG,
    SILTAVE as SILT_PCT_AVG,
    SANDAVE as SAND_PCT_AVG,
    KFACT_UP as ERODIBILITY_FACTOR
from {{ ref('attributes_gageii_Soils') }}
