-- GAGES-II geology attributes
select
    STAID as SITE_ID,
    GEOL_REEDBUSH_DOM as GEOLOGY_CLASS_REEDBUSH,
    GEOL_REEDBUSH_DOM_PCT as GEOLOGY_PCT_REEDBUSH,
    GEOL_HUNT_DOM_CODE as GEOLOGY_CODE_HUNT,
    GEOL_HUNT_DOM_PCT as GEOLOGY_PCT_HUNT,
    GEOL_HUNT_DOM_DESC as GEOLOGY_DESC_HUNT
from {{ ref('attributes_gageii_Geology') }}
