select
    -- Streamflow data (USGS streamflow extractor)
    streamflow.site_id,
    streamflow.observation_hour,
    streamflow.latitude,
    streamflow.longitude,
    streamflow.streamflow_cfs_mean,
    streamflow.streamflow_cfs_max,
    streamflow.streamflow_cfs_min,
    streamflow.gage_height_ft_mean,
    streamflow.gage_height_ft_max,
    streamflow.gage_height_ft_min,
    streamflow.observation_count,

    -- NLDAS-3 forcing data (watershed-averaged)
    streamflow.precipitation_mm,
    streamflow.temperature_c,
    streamflow.wind_speed_ms,
    streamflow.specific_humidity_kgkg,
    streamflow.surface_pressure_pa,
    streamflow.shortwave_radiation_wm2,
    streamflow.longwave_radiation_wm2,
    streamflow.potential_evaporation_mm,
    streamflow.cape_jkg,
    streamflow.convective_precip_fraction,

    -- Site attributes (CAMELSH static attributes via dbt seeds)
    attributes.station_name,
    attributes.latitude,
    attributes.longitude,
    attributes.huc_code,

    -- Basin characteristics
    attributes.drain_sqkm,
    attributes.is_reference_hcdn2009,
    attributes.is_reference_hbn36,

    -- Basin classification
    attributes.agg_ecoregion,
    attributes.hydro_disturbance_index,

    -- Basin morphology
    attributes.basin_compactness,

    -- Boundary QA
    attributes.basin_boundary_confidence,
    attributes.nwis_drainage_area,
    attributes.huc10_check,

    -- Geology
    attributes.geology_class_reedbush,
    attributes.geology_pct_reedbush,
    attributes.geology_site_reedbush,
    attributes.geology_code_hunt,
    attributes.geology_pct_hunt,
    attributes.geology_desc_hunt,


    -- Climate indices (NLDAS-derived)
    attributes.p_mean,
    attributes.pet_mean,
    attributes.aridity_index,
    attributes.p_seasonality,
    attributes.frac_snow,
    attributes.high_prec_freq,
    attributes.high_prec_dur,
    attributes.low_prec_freq,
    attributes.low_prec_dur,

    -- Hydrology
    attributes.streams_km_per_sq_km,
    attributes.strahler_max,
    attributes.mainstem_sinuosity,
    attributes.reach_code,
    attributes.artificial_path_pct,
    attributes.artificial_path_mainstem_pct,
    attributes.hires_lentic_pct,
    attributes.bfi_ave,
    attributes.perdun,
    attributes.perhor,
    attributes.topwet,
    attributes.contact,
    attributes.runave7100,
    attributes.wb5100_ann_mm,
    attributes.pct_1st_order,
    attributes.pct_2nd_order,
    attributes.pct_3rd_order,
    attributes.pct_4th_order,
    attributes.pct_5th_order,
    attributes.pct_6th_order_or_more,
    attributes.pct_no_order,

    -- Hydrology Modification attributes related to dams
    attributes.num_dams,
    attributes.dam_density,
    attributes.storage_nid,
    attributes.storage_nor,
    attributes.num_major_dams,
    attributes.major_dam_density,
    attributes.raw_dis_nearest_dam,
    attributes.raw_avg_dis_all_dams,
    attributes.raw_dis_nearest_maj_dam,
    attributes.raw_avg_dis_all_maj_dams,

    -- Hydrology Modification attributes related to other factors
    attributes.canals_pct,
    attributes.raw_dis_nearest_canal,
    attributes.raw_avg_dis_allcanals,
    attributes.canals_mainstem_pct,
    attributes.npdes_major_density,
    attributes.raw_dis_nearest_maj_npdes,
    attributes.raw_avg_dis_all_maj_npdes,
    attributes.freshwater_withdrawal,
    attributes.mining_pct,
    attributes.pct_irrig_ag,
    attributes.power_num_pts,
    attributes.power_sum_mw,

    -- HydroATLAS key attributes
    attributes.discharge_avg,
    attributes.discharge_min,
    attributes.discharge_max,
    attributes.runoff,
    attributes.inu_pc_smn,
    attributes.inu_pc_smx,
    attributes.inu_pc_slt,
    attributes.lka_pc_use,
    attributes.lkv_mc_usu,
    attributes.rev_mc_usu,
    attributes.dor_pc_pva,
    attributes.ria_ha_usu,
    attributes.riv_tc_usu,
    attributes.gwt_cm_sav,
    attributes.ele_mt_sav,
    attributes.ele_mt_smn,
    attributes.ele_mt_smx,
    attributes.slp_dg_uav,
    attributes.sgr_dk_sav,
    attributes.clz_cl_smj,
    attributes.cls_cl_smj,
    attributes.tmp_dc_syr,
    attributes.tmp_dc_smn,
    attributes.tmp_dc_smx,
    attributes.tmp_dc_s01,
    attributes.tmp_dc_s02,
    attributes.tmp_dc_s03,
    attributes.tmp_dc_s04,
    attributes.tmp_dc_s05,
    attributes.tmp_dc_s06,
    attributes.tmp_dc_s07,
    attributes.tmp_dc_s08,
    attributes.tmp_dc_s09,
    attributes.tmp_dc_s10,
    attributes.tmp_dc_s11,
    attributes.tmp_dc_s12,
    attributes.pet_mm_syr,
    attributes.pet_mm_s01,
    attributes.pet_mm_s02,
    attributes.pet_mm_s03,
    attributes.pet_mm_s04,
    attributes.pet_mm_s05,
    attributes.pet_mm_s06,
    attributes.pet_mm_s07,
    attributes.pet_mm_s08,
    attributes.pet_mm_s09,
    attributes.pet_mm_s10,
    attributes.pet_mm_s11,
    attributes.pet_mm_s12,
    attributes.aet_mm_syr,
    attributes.aet_mm_s01,
    attributes.aet_mm_s02,
    attributes.aet_mm_s03,
    attributes.aet_mm_s04,
    attributes.aet_mm_s05,
    attributes.aet_mm_s06,
    attributes.aet_mm_s07,
    attributes.aet_mm_s08,
    attributes.aet_mm_s09,
    attributes.aet_mm_s10,
    attributes.aet_mm_s11,
    attributes.aet_mm_s12,
    attributes.ari_ix_uav,
    attributes.cmi_ix_syr,
    attributes.cmi_ix_s01,
    attributes.cmi_ix_s02,
    attributes.cmi_ix_s03,
    attributes.cmi_ix_s04,
    attributes.cmi_ix_s05,
    attributes.cmi_ix_s06,
    attributes.cmi_ix_s07,
    attributes.cmi_ix_s08,
    attributes.cmi_ix_s09,
    attributes.cmi_ix_s10,
    attributes.cmi_ix_s11,
    attributes.cmi_ix_s12,
    attributes.snw_pc_syr,
    attributes.snw_pc_smx,
    attributes.snw_pc_s01,
    attributes.snw_pc_s02,
    attributes.snw_pc_s03,
    attributes.snw_pc_s04,
    attributes.snw_pc_s05,
    attributes.snw_pc_s06,
    attributes.snw_pc_s07,
    attributes.snw_pc_s08,
    attributes.snw_pc_s09,
    attributes.snw_pc_s10,
    attributes.snw_pc_s11,
    attributes.snw_pc_s12,
    attributes.glc_cl_smj,
    attributes.glc_pc_u01,
    attributes.glc_pc_u02,
    attributes.glc_pc_u03,
    attributes.glc_pc_u04,
    attributes.glc_pc_u05,
    attributes.glc_pc_u06,
    attributes.glc_pc_u07,
    attributes.glc_pc_u08,
    attributes.glc_pc_u09,
    attributes.glc_pc_u10,
    attributes.glc_pc_u11,
    attributes.glc_pc_u12,
    attributes.glc_pc_u13,
    attributes.glc_pc_u14,
    attributes.glc_pc_u15,
    attributes.glc_pc_u16,
    attributes.glc_pc_u17,
    attributes.glc_pc_u18,
    attributes.glc_pc_u19,
    attributes.glc_pc_u20,
    attributes.glc_pc_u21,
    attributes.glc_pc_u22,
    attributes.pnv_cl_smj,
    attributes.pnv_pc_u01,
    attributes.pnv_pc_u02,
    attributes.pnv_pc_u03,
    attributes.pnv_pc_u04,
    attributes.pnv_pc_u05,
    attributes.pnv_pc_u06,
    attributes.pnv_pc_u07,
    attributes.pnv_pc_u08,
    attributes.pnv_pc_u09,
    attributes.pnv_pc_u10,
    attributes.pnv_pc_u11,
    attributes.pnv_pc_u12,
    attributes.pnv_pc_u13,
    attributes.pnv_pc_u14,
    attributes.pnv_pc_u15,
    attributes.wet_cl_smj,
    attributes.wet_pc_ug1,
    attributes.wet_pc_ug2,
    attributes.wet_pc_u01,
    attributes.wet_pc_u02,
    attributes.wet_pc_u03,
    attributes.wet_pc_u04,
    attributes.wet_pc_u05,
    attributes.wet_pc_u06,
    attributes.wet_pc_u07,
    attributes.wet_pc_u08,
    attributes.wet_pc_u09,
    attributes.for_pc_use,
    attributes.crp_pc_use,
    attributes.pst_pc_use,
    attributes.ire_pc_use,
    attributes.gla_pc_use,
    attributes.prm_pc_use,
    attributes.pac_pc_use,
    attributes.tbi_cl_smj,
    attributes.tec_cl_smj,
    attributes.fmh_cl_smj,
    attributes.fec_cl_smj,
    attributes.cly_pc_uav,
    attributes.slt_pc_uav,
    attributes.snd_pc_uav,
    attributes.soc_th_uav,
    attributes.swc_pc_syr,
    attributes.swc_pc_s01,
    attributes.swc_pc_s02,
    attributes.swc_pc_s03,
    attributes.swc_pc_s04,
    attributes.swc_pc_s05,
    attributes.swc_pc_s06,
    attributes.swc_pc_s07,
    attributes.swc_pc_s08,
    attributes.swc_pc_s09,
    attributes.swc_pc_s10,
    attributes.swc_pc_s11,
    attributes.swc_pc_s12,
    attributes.lit_cl_smj,
    attributes.kar_pc_use,
    attributes.ero_kh_uav,
    attributes.pop_ct_usu,
    attributes.ppd_pk_uav,
    attributes.urb_pc_use,
    attributes.nli_ix_uav,
    attributes.rdd_mk_uav,
    attributes.hft_ix_u93,
    attributes.hft_ix_u09,
    attributes.gad_id_smj,
    attributes.gdp_ud_usu,
    attributes.hdi_ix_sav,

    -- Landscape pattern attributes
    attributes.fragun_basin,
    attributes.hires_lentic_num,
    attributes.hires_lentic_dens,
    attributes.hires_lentic_meansiz,

    -- Landscape crop attributes
    attributes.cdl_corn,
    attributes.cdl_cotton,
    attributes.cdl_rice,
    attributes.cdl_sorghum,
    attributes.cdl_soybeans,
    attributes.cdl_sunflowers,
    attributes.cdl_peanuts,
    attributes.cdl_barley,
    attributes.cdl_durum_wheat,
    attributes.cdl_spring_wheat,
    attributes.cdl_winter_wheat,
    attributes.cdl_wwht_soy_dbl_crop,
    attributes.cdl_oats,
    attributes.cdl_alfalfa,
    attributes.cdl_other_hays,
    attributes.cdl_dry_beans,
    attributes.cdl_potatoes,
    attributes.cdl_fallow_idle,
    attributes.cdl_pasture_grass,
    attributes.cdl_oranges,
    attributes.cdl_other_crops,
    attributes.cdl_all_other_land,

    -- Landscape Basin
    attributes.dev_nlcd06,
    attributes.forest_nlcd06,
    attributes.plant_nlcd06,
    attributes.water_nlcd06,
    attributes.snow_ice_nlcd06,
    attributes.dev_open_nlcd06,
    attributes.dev_low_nlcd06,
    attributes.dev_med_nlcd06,
    attributes.dev_high_nlcd06,
    attributes.barren_nlcd06,
    attributes.deciduous_nlcd06,
    attributes.evergreen_nlcd06,
    attributes.mixed_forest_nlcd06,
    attributes.shrub_nlcd06,
    attributes.grass_nlcd06,
    attributes.pasture_nlcd06,
    attributes.crops_nlcd06,
    attributes.woody_wet_nlcd06,
    attributes.emergent_wet_nlcd06,

    -- Landscape Mainstem attributes with 100m buffer, 2006 era
    attributes.mains100_dev,
    attributes.mains100_forest,
    attributes.mains100_plant,
    attributes.mains100_11,
    attributes.mains100_12,
    attributes.mains100_21,
    attributes.mains100_22,
    attributes.mains100_23,
    attributes.mains100_24,
    attributes.mains100_31,
    attributes.mains100_41,
    attributes.mains100_42,
    attributes.mains100_43,
    attributes.mains100_52,
    attributes.mains100_71,
    attributes.mains100_81,
    attributes.mains100_82,
    attributes.mains100_90,
    attributes.mains100_95,

    -- Landscape Mainstem attributes with 800m buffer, 2006 era
    attributes.mains800_dev,
    attributes.mains800_forest,
    attributes.mains800_plant,
    attributes.mains800_11,
    attributes.mains800_12,
    attributes.mains800_21,
    attributes.mains800_22,
    attributes.mains800_23,
    attributes.mains800_24,
    attributes.mains800_31,
    attributes.mains800_41,
    attributes.mains800_42,
    attributes.mains800_43,
    attributes.mains800_52,
    attributes.mains800_71,
    attributes.mains800_81,
    attributes.mains800_82,
    attributes.mains800_90,
    attributes.mains800_95,

    -- Landscape Riparian attributes with 100m buffer, 2006 era
    attributes.rip100_dev,
    attributes.rip100_forest,
    attributes.rip100_plant,
    attributes.rip100_11,
    attributes.rip100_12,
    attributes.rip100_21,
    attributes.rip100_22,
    attributes.rip100_23,
    attributes.rip100_24,
    attributes.rip100_31,
    attributes.rip100_41,
    attributes.rip100_42,
    attributes.rip100_43,
    attributes.rip100_52,
    attributes.rip100_71,
    attributes.rip100_81,
    attributes.rip100_82,
    attributes.rip100_90,
    attributes.rip100_95,

    -- Landscape Riparian attributes with 800m buffer, 2006 era
    attributes.rip800_dev,
    attributes.rip800_forest,
    attributes.rip800_plant,
    attributes.rip800_11,
    attributes.rip800_12,
    attributes.rip800_21,
    attributes.rip800_22,
    attributes.rip800_23,
    attributes.rip800_24,
    attributes.rip800_31,
    attributes.rip800_41,
    attributes.rip800_42,
    attributes.rip800_43,
    attributes.rip800_52,
    attributes.rip800_71,
    attributes.rip800_81,
    attributes.rip800_82,
    attributes.rip800_90,
    attributes.rip800_95,

    -- Nutrient Application
    attributes.nitr_app_kg_sqkm,
    attributes.phos_app_kg_sqkm,

    -- Pesticides Application
    attributes.pestapp_kg_sqkm,

    -- Population and infrastructure attributes
    attributes.pden_2000_block,
    attributes.pden_day_landscan_2007,
    attributes.pden_night_landscan_2007,
    attributes.roads_km_sq_km,
    attributes.rd_str_inters,
    attributes.impnlcd06,
    attributes.nlcd01_06_dev,

    -- Protected Areas
    attributes.padcat1_pct_basin,
    attributes.padcat2_pct_basin,
    attributes.padcat3_pct_basin,

    -- Regions
    attributes.eco3_site,
    attributes.hlr100m_site,
    attributes.huc8_site,
    attributes.nutr_eco_site,
    attributes.usda_lrr_site,
    attributes.eco2_bas_dom,
    attributes.eco3_bas_dom,
    attributes.eco3_bas_pct,
    attributes.hlr_bas_dom_100m,
    attributes.hlr_bas_pct_100m,
    attributes.nutr_bas_dom,
    attributes.nutr_bas_pct,
    attributes.pnv_bas_dom,
    attributes.pnv_bas_pct,

    -- Soils
    attributes.hga,
    attributes.hgb,
    attributes.hgad,
    attributes.hgc,
    attributes.hgd,
    attributes.hgac,
    attributes.hgb_d,
    attributes.hgcd,
    attributes.hgbc,
    attributes.hgvar,
    attributes.soil_water_capacity_avg,
    attributes.soil_permeability_avg,
    attributes.bulk_density_avg,
    attributes.organic_matter_avg,
    attributes.water_table_depth_avg,
    attributes.rock_depth_avg,
    attributes.no4_ave,
    attributes.no200_ave,
    attributes.no10_ave,
    attributes.clay_pct_avg,
    attributes.silt_pct_avg,
    attributes.sand_pct_avg,
    attributes.erodibility_factor,
    attributes.runoff_factor,

    -- Topography
    attributes.elev_mean_m,
    attributes.elev_max_m,
    attributes.elev_min_m,
    attributes.elev_median_m,
    attributes.elev_std_m,
    attributes.elev_site_m,
    attributes.relief_ratio_mean,
    attributes.relief_ratio_median,
    attributes.slope_pct,
    attributes.aspect_deg,
    attributes.aspect_northness,
    attributes.aspect_eastness,

    lead(streamflow.streamflow_cfs_mean, 1) over (
        partition by streamflow.site_id
        order by streamflow.observation_hour
    ) as streamflow_cfs_target_1h,
    lead(streamflow.gage_height_ft_mean, 1) over (
        partition by streamflow.site_id
        order by streamflow.observation_hour
    ) as gage_height_ft_target_1h
from {{ ref('fct_streamflow_hourly') }} as streamflow
inner join {{ ref('dim_catchment_attributes') }} as attributes
    on streamflow.site_id = attributes.site_id
